Primecomp93Helix/src/Feature/PageContent/code/Controllers/ReportCenterController.cs
using Primecomp93Helix.Feature.PageContent.Helpers;
using Primecomp93Helix.Feature.PageContent.Models;
using Sitecore.Data;
using Sitecore.Data.Fields;
using Sitecore.Data.Items;
using Sitecore.Pipelines;
using Sitecore.Resources.Media;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Sitecore.Configuration;


namespace Primecomp93Helix.Feature.PageContent.Controllers
{
    public class ReportCenterController : Controller
    {
        private static readonly string StrReportCenterParentId = Settings.GetSetting("reportCenterParentID");
        // GET: ReportCenter
        public ActionResult Index()
        {
            if (Sitecore.Context.User.IsAuthenticated)
            {
                return View();

            }
            else
            {
                return Redirect("~/Home/");
            }
        }
        #region DocumentQuery
        [HttpPost]
        public JsonResult DocumentQuery(SitecoreQuery obj)
        {
            try
            {
                // Map Results to Document Model
                List<Document> Documents = new List<Document>();
                PropertyInfo[] properties = typeof(Document).GetProperties();

                Database db = Sitecore.Configuration.Factory.GetDatabase("web");
                Item parentItem = db.GetItem(StrReportCenterParentId);

                var children = parentItem.GetChildren(Sitecore.Collections.ChildListOptions.SkipSorting)
                    .OrderBy(f => f.Fields["Title"].ToString())
                    .ToList();
                
                SitecoreResponse response = Search(children, obj);

                foreach (Dictionary<string, object> doc in response.Results)
                {
                    Document document = new Document();

                    foreach (PropertyInfo prop in properties)
                    {
                        object value = "";
                        if (doc.TryGetValue(prop.Name, out value))
                        {
                            // change thumbnail size, can handle from front end as well
                            if (prop.Name.Equals("Thumbnail"))
                            {
                                prop.SetValue(document, value.ToString().Replace("16", "50"));
                            }
                            else if (prop.Name.ToLower().Equals("extension"))
                            {
                                switch (value.ToString().ToLower())
                                {
                                    case "pdf":
                                        {
                                            prop.SetValue(document, "pdf.png");
                                            break;
                                        }
                                    case "doc":
                                    case "docx":
                                        {
                                            prop.SetValue(document, "word.png");
                                            break;
                                        }
                                    case "xls":
                                    case "xlsx":
                                        {
                                            prop.SetValue(document, "excel.png");
                                            break;
                                        }
                                    case "rtf":
                                        {
                                            prop.SetValue(document, "rtf-icon.png");
                                            break;
                                        }
                                    case "txt":
                                        {
                                            prop.SetValue(document, "txt-icon.png");
                                            break;
                                        }
                                    case "pptx":
                                        {
                                            prop.SetValue(document, "pptx-icon.png");
                                            break;
                                        }
                                    default:
                                        {
                                            prop.SetValue(document, "alternatedoc.png");
                                            break;
                                        }
                                }
                            }
                            else
                            {
                                prop.SetValue(document, value);
                            }
                        }
                        else
                        {
                            prop.SetValue(document, null);
                        }
                    }
                    Documents.Add(document);
                }

                // Map Views to Response
                JsonResponse json = new JsonResponse();

                // etc
                json.TotalHits = response.TotalHits;
                json.OriginalQuery = response.OriginalQuery;

                //results
                json.Results = ViewHelper.RenderViewToString(this.ControllerContext, "_SearchResults", new DocumentResultView()
                {
                    Start = obj.Start,
                    Documents = Documents
                });

                // facets
                RenderFacetView(response, "__semantics", json, "_FacetCheckboxes");

                return Json(json);
            }
            catch (Exception e)
            {
                return BuildJsonErrorResponse(e);
            }
        }
        #endregion

        #region DocumentSearch
        public static SitecoreResponse Search(List<Item> master, SitecoreQuery obj)
        {
            List<Item> list = new List<Item>();
            SitecoreResponse response = new SitecoreResponse();

            List<Item> temp = new List<Item>();
            List<Item> filteredList = new List<Item>();
            if (!obj.query.Equals("*"))
            {
                foreach (var item in master)
                {
                    StringBuilder fullmatch = new StringBuilder(item.Fields["Title"].ToString());

                    if (fullmatch.ToString().Equals(obj.query.ToString(), StringComparison.InvariantCultureIgnoreCase))
                    {
                        temp.Add(item);
                    }
                    else
                    {
                        if (item.Fields["Title"].Value.ToUpper().ToString().Contains(obj.query.ToUpper()))
                        {
                            temp.Add(item);
                        }
                    }
                    if (obj.Filters.Count > 0)
                    {
                        filteredList = Filter(temp, obj);
                    }
                    else
                    {
                        filteredList = temp;
                    }
                }

                try
                {
                    List<Item> newlist = new List<Item>();
                    if (obj.Sort != null && obj.Sort.Equals("desc"))
                    {
                        list = filteredList.Where(x => x.Fields["Extension"].ToString() != "mdb")
                            .OrderByDescending(x => x.Fields["Title"].Value.ToString())
                            .ToList();
                        var filter = list.Skip(obj.Start)
                            .Take(10).ToList();
                        response.TotalHits = list.Count;
                    }
                    else
                    {
                        list = filteredList.Where(x=>x.Fields["Extension"].ToString()!="mdb")
                            .OrderBy(x => x.Fields["Title"].Value.ToString())
                            .ToList();
                        var filter = list.Skip(obj.Start)
                            .Take(10).ToList();
                        response.TotalHits = list.Count;
                    }

                    
                }

                catch (Exception e)
                {
                    Sitecore.Diagnostics.Log.Error("PhysicianPortal.Controllers.FAPController.Search ", e.Message);
                }
            }
            else
            {
                try
                {
                    if (obj.Filters.Count > 0)
                    {
                        //filter results before sorting and picking
                        filteredList = Filter(master, obj);
                    }
                    else
                    {
                        filteredList = master;
                    }
                    //list.Clear();
                    if (obj.Sort != null && obj.Sort.Equals("desc"))
                    {
                        var children = filteredList
                            .Where(x => x.Fields["Extension"].ToString() != "mdb")
                            .OrderByDescending(e => e.Fields["Title"].Value.ToString())
                            .ToList();
                        var filter = children.Skip(obj.Start)
                            .Take(10).ToList();
                        list = filter;
                        response.TotalHits = children.Count;
                    }
                    else
                    {
                        var children = filteredList
                            .Where(x => x.Fields["Extension"].ToString() != "mdb")
                            .OrderBy(e => e.Fields["Title"].Value.ToString())
                            .ToList();
                        var filter = children.Skip(obj.Start)
                            .Take(10).ToList();

Primecomp93Helix/src/Feature/PageContent/code/Views/ReportCenter/Index.cshtml
@using Sitecore.Mvc
<link href="~/Content/ReportCenter.css" rel="stylesheet" />

<div class="container bg-white">
    <h1 class="dcenter-header">@Html.Sitecore().Field("Title")</h1><br>
    <form id="docCenterSearchForm">
        <div class="row">
            <div class="col-md-10 col-xs-9">
                <input id="query" type="text" name="query" placeholder="Enter Search Term" class="form-control" autofocus />
            </div>
            <div class="col-md-2 col-md-push-0 col-sm-2 col-xs-3">
                <button type="submit" class="dcenter-search-btn"><span class="fa fa-search"></span></button>
            </div>
        </div>
    </form><br>
    <div class="row">
        <div class="col-md-6">
            <div class="dcenter-sort-wrap">
                <label class="dcenter-sort-label hidden-xs">
                    Show
                    <select id="option-sort" class="form-control dcenter-sort">
                        <option value="10">10</option>
                        <option value="20">20</option>
                        <option value="30">30</option>
                        <option value="40">40</option>
                        <option value="50">50</option>
                    </select>entries
                </label>
            </div>


        </div>
        <div class="dcenter-topsort-margin col-md-3">

        </div>
    </div>
    @*<div class="row visible-xs visible-sm">
        <div class="col-md-12">
            <div class="dcenter-result-filter">
                <p>
                    <a id="dcenter-filter-toggle">
                        Upload new Document
                        <i class="fa fa-chevron-up" aria-hidden="true"></i>
                    </a>
                </p>
            </div>
        </div>
    </div>*@

    <div class="row">
        <div class=" col-md-12 dcenter-refine-show hidden-xs hidden-sm" id="dcenter-showing-top">Showing 0 - 0 of 0 entries</div>

        @*<div class="col-md-3">
            @if (Sitecore.Security.Accounts.User.Current.IsInRole("sitecore\\Admin"))
            {
                <div class="dcenter-filters-container">
                    <form action="@Url.Action("AddMediaItem", "ReportCenter")" method="post" enctype="multipart/form-data">
                        <input type="file" name="document" />
                        <button class="dcenter-download dcenter-download-btn" type="submit">
                            <i class="fa fa-upload" aria-hidden="true"> UPLOAD</i>
                        </button>
                    </form>
                </div>
            }
        </div>*@

        <div class="col-md-9">
            <div class="dcenter-results-container">
                <ul id="results" class="dcenter-results"></ul>
            </div>
            <div class="dcenter-controls-container row">

                <div class="col-md-6 dcenter-bottom-showing" id="dcenter-showing-bottom">Showing 0 - 0 of 0 entries</div>
                <div id="pagination" class="col-md-6"></div>

            </div>

        </div>
    </div>
</div>

<script type="text/javascript" src="~/Scripts/ReportCenter.js"></script>

Primecomp93Helix/src/Feature/PageContent/code/Views/ReportCenter/_FacetCheckboxes.cshtml
@using Sitecore.Data;
@using Sitecore.Data.Items;
@model Primecomp93Helix.Feature.PageContent.Models.FacetView

@if (Model != null)
{
    <div class="radio">
        <label>
            <input class="dcenter-listradio" name="docCat" id="r1" type="radio" value="" @if ((Model.Filter == null) || ((Model.Filter.Count == 1) && (Model.Filter[0].Equals("")))) { <text> checked</text> } />All
        </label>
    </div>
    foreach (KeyValuePair<string, int>
                        item in Model.Facet.Value)
    {
        ID tagID = new Sitecore.Data.ID(item.Key);
        Item tagItem = Sitecore.Context.Database.GetItem(tagID);
        @*<input type="radio" name="@Model.Facet.Key" value="@item.Key" @if (Model.Filter.Contains(@item.Key)) { <text> checked</text> }>@item.Key <text>-</text> @item.Value<br/>*@

        <div class="radio">
            <label>
                @*<input type="radio" name="@Model.Facet.Key" value="@tagItem.Name" @if (Model.Filter.Contains(@tagItem.Name)) { <text> checked</text> }>@item.Key <text>-</text> @item.Value<br/>*@
                <input class="dcenter-listradio" name="docCat" id="r1" type="radio" value="@item.Key" @if (Model.Filter.Contains(item.Key)) { <text> checked</text> } />@tagItem.Name

            </label>
        </div>
    }
}

<script>
    $(document).ready(function () {
        var selector = ".dcenter-listradio";
        $(selector).change(function () {
            //if (this.checked) {
            //    $(selector).not(this).prop('checked', false);
            //}
            main();
        });
    });
</script>

Primecomp93Helix/src/Feature/PageContent/code/Views/ReportCenter/_SearchResults.cshtml
@using Sitecore.Mvc;
@model Primecomp93Helix.Feature.PageContent.Models.DocumentResultView

@if (Model != null)
{
    if (Model.Documents != null && Model.Documents.Count > 0)
    {
        var count = Model.Start + 1;

        foreach (var item in Model.Documents)
        {
            <li class="dcenter-result">

                <div class="row">
                    <div class="col-xs-4 col-sm-2 col-md-2">
                        <div class="dcenter-result-image">
                            <img alt='No Image' src='@string.Format("/Images/{0}", @item.Extension)' />
                        </div>
                    </div>
                    <div class="col-xs-8 col-sm-8 col-md-8">
                        <div class="dcenter-name">
                            <a href="@Url.Action("Download", "ReportCenter", new { FilePath = item.Path })"
                               type="submit"
                               id="runReport"
                               target="_blank"
                               class="dcenter-url">
                                @(!String.IsNullOrEmpty(item.Title) ? item.Title : item.BackupTitle)
                            </a>

                            @*<a class="dcenter-url" href='#'>
                                    @(!String.IsNullOrEmpty(item.Title) ? item.Title : item.BackupTitle)
                                </a>*@

                            @if ((DateTime.Now - @item.Created).TotalDays < 10)
                            {
                                <br class="visible-xs hidden-md hidden-lg" /><span class="dcenter-title-span2">new</span>
                            }

                        </div>
                        <p>@item.Description</p>
                        <ul class="dcenter-doc-detail">
                            <li>Date Created: <span id="dcenter-dateCreated">@item.Created</span></li>
                            <li>Date Updated: @item.Updated</li>
                            @*<li>Category:</li>
                                <span>Legal</span>*@
                        </ul>

                    </div>

                    <div class="col-xs-4 col-xs-push-4   col-sm-1 col-sm-push-0 col-md-2 col-md-push-0">
                        <a href="@Url.Action("Download", "ReportCenter", new { FilePath = item.Path })"
                           type="submit"
                           id="runReport"
                           target="_blank"
                           class="dcenter-url">
                            <button class="dcenter-download dcenter-download-btn">
                                <i class="fa fa-download" aria-hidden="true"></i>
                            </button>
                        </a>


                    </div>
                </div>
                <hr class="dcenter-result-hr">
            </li>
        }
    }
    else
    {
        <div class="col-xs-3 hidden-xs"></div>
        <div class="col-xs-2 hidden-lg"></div>
        <div class="col-xs-9 dcenter-nodoc">No documents found</div>
    }


}