Primecomp93Helix/src/Feature/PageContent/code/Models/Header.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Primecomp93Helix.Feature.PageContent.Models
{
    public class Header
    {
        public Menu Menu { get; set; }
        public List<MenuItem> MenuItems { get; set; }
        public List<Nav> Nav { get; set; }
    }

    public class Menu
    {
        public string SiteLogo { get; set; }
        public string SiteLogoURL { get; set; }
        public bool GetAuthMenu { get; set; }
        public List<MenuItem> MenuItem { get; set; }
    }
    public class MenuItem
    {
        public string MenuItemText { get; set; }
        public string MenuItemLogo { get; set; }
        public string MenuItemURL { get; set; }
        public MenuItem()
        {
            MenuItemText = "";
            MenuItemLogo = "";
            MenuItemURL = "";
        }
    }   
    public class Nav
    {
        public string NavItemText { get; set; }
        public string NavItemURL { get; set; }
        public List<NavLinks> NavLinks { get; set; }
    }
    public class NavLinks
    {
        public string NavLinkText { get; set; }
        public string NavLinkURL { get; set; }
    }
    public class Breadcrumb
    {
        public List<Crumb> Crumtrail { get; set; }
    }
    public class Crumb
    {
        public string Text { get; set; }
        public string Url { get; set; }
        public string Type { get; set; }
    }
}

Primecomp93Helix/src/Feature/PageContent/code/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Primecomp93Helix.Feature.PageContent.Models;
using Sitecore.Configuration;
using Sitecore.Data;
using Sitecore.Data.Fields;
using Sitecore.Data.Items;
using Sitecore.Links;

namespace Primecomp93Helix.Feature.PageContent.Controllers
{
    public class SharedController : Controller
    {
        private readonly string _headerItem = Settings.GetSetting("HeaderItem");

        private readonly string _headerDetails = Settings.GetSetting("HeaderDetails");

        private readonly string _blogId = Settings.GetSetting("BlogID");
        // GET: Shared
    
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Header()
        {
            Header _header = new Header
            {
                Menu = new Menu(),
                MenuItems = new List<MenuItem>(),
                Nav = new List<Nav>()
            };

            Sitecore.Diagnostics.Log.Debug("Header -> made it into _header: ");

            try
            {
                var defaultUrlOptions = LinkManager.GetDefaultUrlBuilderOptions();
                defaultUrlOptions.EncodeNames = true;
                ID menuItemId = new ID(_headerItem);
                Item HeaderMenuItem = Sitecore.Context.Database.GetItem(menuItemId);  // ("/sitecore/content/Components/Header Control/Header");

                ImageField imageField = HeaderMenuItem.Fields["Logo"];
                if (imageField != null && imageField.MediaItem != null)
                {
                    MediaItem siteLogo = new MediaItem(imageField.MediaItem);
                    _header.Menu.SiteLogoURL = Sitecore.StringUtil.EnsurePrefix('/', Sitecore.Resources.Media.MediaManager.GetMediaUrl(siteLogo));
                    _header.Menu.SiteLogo = siteLogo.Alt;
                }
                MultilistField headerMenuList = null;
                ID navList = null;
                string strHeaderDetails = _headerDetails;
                headerMenuList = HeaderMenuItem.Fields[strHeaderDetails];
                navList = new ID(strHeaderDetails);
                
                #region // Nav Links
                Item headerNavList = Sitecore.Context.Database.GetItem(navList);
                MultilistField headerNavMulList = null;
                headerNavMulList = headerNavList.Fields["Navigation Links"];
                ID strBlogID = new ID(_blogId);
                foreach (Item parentNavItem in headerNavMulList.GetItems())
                {
                    // don't build children for blog
                    
                    List<Item> childItems = null;
                    childItems = parentNavItem.GetChildren().ToList();
                    List<NavLinks> _childNavItem = new List<NavLinks>();
                    Sitecore.Diagnostics.Log.Info("BlogID= " + strBlogID.ToString() + " ParentNavItem.ID= " + parentNavItem.ID.ToString(), strBlogID);
                    if (strBlogID != parentNavItem.ID)
                    {
                        foreach (Item child in childItems)
                        {
                          // print out all the childitems
                          Sitecore.Diagnostics.Log.Info("Child Item: " + child.ID + " " + child.Name + " " + child.ParentID + " " + child.Parent.Name + " ", child);
                          if (child.ParentID == strBlogID)
                          {
                            Sitecore.Diagnostics.Log.Info("child.ParentID= " + child.ParentID + " == " + strBlogID, child);
                            continue;
                          }
                          _childNavItem.Add(new NavLinks
                          {
                              NavLinkText = child.DisplayName,

                              NavLinkURL = LinkManager.GetItemUrl(child, defaultUrlOptions) //.Paths.Path
                          });
                        }
                    }
                    _header.Nav.Add(new Nav
                    {
                        NavItemText = parentNavItem.DisplayName,
                        NavItemURL = LinkManager.GetItemUrl(parentNavItem, defaultUrlOptions), //parentNavItem.Paths.Path,
                        NavLinks = _childNavItem
                    });
                }
                #endregion
                return PartialView(_header);
            }
            catch (Exception ex)
            {
                Sitecore.Diagnostics.Log.Info("Shared Header Exception : " + ex.ToString(), this);
                return null;
            }
            //return PartialView(_header);
        }
        public ActionResult HeaderFAP()
        {
            Header _header = new Header
            {
                Menu = new Menu(),
                MenuItems = new List<MenuItem>(),
                Nav = new List<Nav>()
            };

            Sitecore.Diagnostics.Log.Debug("Header -> made it into _header: ");

            try
            {
                var defaultUrlOptions = LinkManager.GetDefaultUrlBuilderOptions();
                defaultUrlOptions.EncodeNames = true;
                ID menuItemId = new ID(_headerItem);
                Item HeaderMenuItem = Sitecore.Context.Database.GetItem(menuItemId);  // ("/sitecore/content/Components/Header Control/Header");

                ImageField imageField = HeaderMenuItem.Fields["Logo"];
                if (imageField != null && imageField.MediaItem != null)
                {
                    MediaItem siteLogo = new MediaItem(imageField.MediaItem);
                    _header.Menu.SiteLogoURL = Sitecore.StringUtil.EnsurePrefix('/', Sitecore.Resources.Media.MediaManager.GetMediaUrl(siteLogo));
                    _header.Menu.SiteLogo = siteLogo.Alt;
                }
                MultilistField headerMenuList = null;
                ID navList = null;
                string strHeaderDetails = _headerDetails;
                headerMenuList = HeaderMenuItem.Fields[strHeaderDetails];
                navList = new ID(strHeaderDetails);

                #region // Nav Links
                Item headerNavList = Sitecore.Context.Database.GetItem(navList);
                MultilistField headerNavMulList = null;
                headerNavMulList = headerNavList.Fields["Navigation Links"];
                ID strBlogID = new ID(_blogId);
                foreach (Item parentNavItem in headerNavMulList.GetItems())
                {
                    // don't build children for blog

                    List<Item> childItems = null;
                    childItems = parentNavItem.GetChildren().ToList();
                    List<NavLinks> _childNavItem = new List<NavLinks>();
                    if (strBlogID != parentNavItem.ID)
                    {
                        foreach (Item child in childItems)
                        {
                            _childNavItem.Add(new NavLinks
                            {
                                NavLinkText = child.DisplayName,
                                NavLinkURL = LinkManager.GetItemUrl(child, defaultUrlOptions) //.Paths.Path
                                //NavLinkURL = child.Paths.Path
                            });
                        }
                    }
                    _header.Nav.Add(new Nav
                    {
                        NavItemText = parentNavItem.DisplayName,
                        NavItemURL = LinkManager.GetItemUrl(parentNavItem, defaultUrlOptions),
                        //NavItemURL = parentNavItem.Paths.Path,
                        NavLinks = _childNavItem
                    });
                }
                #endregion
                return PartialView(_header);
            }
            catch (Exception ex)
            {
                Sitecore.Diagnostics.Log.Info("Shared Header Exception : " + ex.ToString(), this);
                return null;
            }
        }
        public ActionResult Footer()
        {
            return PartialView();
        }
        public ActionResult Breadcrumb()
        {
            Breadcrumb breadcrumb = new Breadcrumb();
            if (breadcrumb!=null)
            {
                return PartialView(breadcrumb);
            }
            else
            {
                return null;
            }
        }

        public ActionResult logout()
        {
            Sitecore.Security.Authentication.AuthenticationManager.Logout();
            Response.Cookies.Clear();
            Session.Abandon();
            System.Web.Security.FormsAuthentication.SignOut();
            return Redirect("/Home");
        }
    }
}

Primecomp93Helix/src/Feature/PageContent/code/Views/Shared/_Layout.cshtml
@using Sitecore.Mvc
    <div>
        @RenderBody()
    </div>

Primecomp93Helix/src/Feature/PageContent/code/Views/Shared/_bodyText.cshtml
@using Sitecore.Mvc

<div id="content-body">
    @Html.Sitecore().Field("body")
</div>

Primecomp93Helix/src/Feature/PageContent/code/Views/Shared/_contentHeading.cshtml
@using Sitecore.Mvc
<div id="content-left-column">
    <div id="content-heading">
        @Html.Sitecore().Field("heading")
    </div>
    <div id="content-subheading-content">
        @Html.Sitecore().Field("subheading")
    </div>
</div>

Primecomp93Helix/src/Feature/PageContent/code/Views/Shared/footer.cshtml
        <div class="col-sm-4 left-sec-foot">
            <div class="col-sm-3">
                <p style="color:white;font-size:x-large;">Follow Us!</p>
            </div>
            <p class="col-sm-3 facebook fb-like" data-href="https://www.facebook.com/PrimeCompNetwork" data-layout="button_count" data-action="like" data-size="small" data-show-faces="false" data-share="false">
            </p>
            <p class="col-sm-3">
                <script src="//platform.linkedin.com/in.js" type="text/javascript">lang: en_US</script>
                <script type="IN/FollowCompany" data-id="25043385">
                </script>
            </p>
            <p class="col-sm-3">
                <a class="twitter-follow-button" href="https://twitter.com/PrimeCompJax" data-size="medium" data-show-screen-name="false" data-show-count="false">PrimeCompJax</a>
                <script async="" src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </p>
        </div>
        <div class="col-sm-4 middle-sec-foot"> 
            <p class="text-center">Prime Comp Network  <br /> 841 Prudential Drive <br /> Suite 1530 <br /> Jacksonville, FL 32207</p>
        </div>
        <div class="col-sm-4 right-foot-sec">
            <p>Phone: <span ><a href="tel:9043763790">(904) 376-3790</a></span></p>
            <p>Fax: <span style="color: black !important;font-weight: bold;text-decoration: underline !important">(904) 391-5321</span></p>
            <p>
                Email: <span>
                    <a href="mailto:primecomp@bmcjax.com">
                        <span>primecomp@bmcjax.com</span>
                    </a>
                </span>
            </p>
        </div>
   

Primecomp93Helix/src/Feature/PageContent/code/Views/Shared/header.cshtml
@using Sitecore.Mvc;
@using Primecomp93Helix.Feature.PageContent.Models
@model Header
<div class="to-header">
    <div>
        <div class="col-sm-12 logo">
            @if (Model != null && Model.Menu != null)
            {
                <a href="/"><img src="@Model.Menu.SiteLogoURL" class="img-responsive logo" /></a>
            }
            else
            {
                <img src="~/Images/Prime Comp_CLR-Resized.jpg" class="img-responsive logo">
            }
        </div>
    </div>
</div>
<!-- This is the middle Nav-->
<div class="header-nav-wrap">
    <nav class="navbar-inverse" data-spy="affix" data-offset-top="5">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <button type="button" class="navbar-toggle" data-toggle="modal" data-target="#myModal">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
            </div>
            <div class="navbar">
                <div class="collapse navbar-collapse" id="myNavbar">
                    <div class="container">
                        <ul class="nav top-nav">
                            <div class="dropdown">
                                <li class="dropbtn" data-title="">
                                    <a href="/">Home</a>
                                </li>
                            </div>
                            <!--<div class="dropdown">
                                <li class="dropbtn" data-title="">-->
                                    @*<a href="@Html.Raw("/sitecore/content/Home/PCNNews")">PCN News</a>*@
                                    <!--<a href="@Html.Raw("/en/PCNNews")">PCN News</a>
                                </li>
                            </div>-->
                            @if (Model != null && Model.Nav != null)
                            {
                                foreach (var nav in Model.Nav)
                                {
                                    <div class="dropdown">
                                        <li class="dropbtn" data-title="">
                                            <a href='@nav.NavItemURL'>
                                                @nav.NavItemText
                                            </a>
                                        </li>

                                        @if (nav.NavLinks != null && nav.NavLinks.Count > 0)
                                        {
                                            <div class="dropdown-content">
                                                @foreach (var navLinks in nav.NavLinks)
                                                {
                                                    if (navLinks.NavLinkText == "Report Center")
                                                    {
                                                        if (Sitecore.Context.User.IsAuthenticated)
                                                        {
                                                            <a href="@navLinks.NavLinkURL">@navLinks.NavLinkText</a>
                                                        }
                                                    }
                                                    else
                                                    {
                                                        <a href='@navLinks.NavLinkURL'>@navLinks.NavLinkText</a>
                                                    }

                                                }
                                            </div>
                                        }
                                    </div>
                                }
                                if (Sitecore.Context.User.IsAuthenticated)
                                {
                                    var sitecoreString = "sitecore\\";
                                    var userName = Sitecore.Context.User.Name.ToString();
                                    userName = userName.Replace(sitecoreString, "");
                                    //DisplayName.ToString();

                                    <div class="dropdown" style="float: right">
                                        @using (Html.BeginForm("logout", "Shared", FormMethod.Post))
                                        {
                                            <div style="padding-top:5px">
                                                <button name="logout" type="submit" value="logout" class="btn btn-info btn-md"><span class="glyphicon glyphicon-log-out"></span> Log out</button>
                                            </div>
                                        }
                                    </div>
                                    <div class="dropdown" style="float: right">

                                        <li class="dropbtn">
                                            @if (userName != null)
                                            {
                                                <div style="color:black; font-weight:bold"> @userName</div>
                                            }
                                        </li>
                                    </div>

                                }
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content nav-modal">
            <div class="modal-header nav-modal-head">
                <div class="row modal-icons-parent">
                    <ul class="modal-icons col-xs-12 list-style-none">
                        <div class="dropdown">
                            <li class="dropbtn" data-title="">
                                <a href="/">Home</a>
                            </li>
                        </div>
                        @if (Model != null && Model.Menu != null && Model.MenuItems != null)
                        {
                            foreach (var menuItem in Model.MenuItems)
                            {
                                <li>
                                    <a href='@menuItem.MenuItemURL'>
                                        <figure><div class="imgicon"><img src='@menuItem.MenuItemLogo' class="img-responsive"></div><figcaption>@menuItem.MenuItemText</figcaption></figure>
                                    </a>
                                </li>
                            }
                        }
                    </ul>

                </div>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                @if (Model != null && Model.Nav != null)
                {
                    foreach (var nav in Model.Nav)
                    {
                        <label class="modal-navHeader"><a href='@nav.NavItemURL'>@nav.NavItemText</a></label>
                        if (nav.NavLinks != null && nav.NavLinks.Count > 0)
                        {
                        <div class="modal-navLinks">
                            <div class="dropdown-content">
                                <ul>

                                    @foreach (var navLinks in nav.NavLinks)
                                    {
                                        if (navLinks.NavLinkText == "Report Center")
                                        {
                                            if (Sitecore.Context.User.IsAuthenticated)
                                            {
                                                <a class=" fa fa-caret-right" href="@navLinks.NavLinkURL"> @navLinks.NavLinkText</a>
                                            }
                                        }
                                        else
                                        {
                                            <a class=" fa fa-caret-right" href='@navLinks.NavLinkURL'> @navLinks.NavLinkText</a>
                                        }
                                    }

                                </ul>
                            </div>
                        </div>
                        }
                    }
                            <div>
                                @if (Sitecore.Context.User.IsAuthenticated)
                                {
                                    var sitecoreString = "sitecore\\";
                                    var userName = Sitecore.Context.User.Name.ToString();
                                    userName = userName.Replace(sitecoreString, "");
                                    //DisplayName.ToString();

                                    <div style="display: flex; justify-content: flex-end">
                                        @if (userName != null)
                                        {
                                            <div  style="padding-right: 5%; color:black; font-weight:bold"> @userName</div>
                                        }
                                    </div>
                                    <div style="display: flex; justify-content: flex-end">
                                        @using (Html.BeginForm("logout", "Shared", FormMethod.Post))
                                        {
                                            <div style="padding-top:5px">
                                                <button name="logout" type="submit" value="logout" class="btn btn-info btn-md"><span class="glyphicon glyphicon-log-out"></span> Log out</button>
                                            </div>
                                        }
                                    </div>

                                }
                            </div> 
                }
            </div>
        </div>
    </div>
</div>

Primecomp93Helix/src/Feature/PageContent/code/Views/Shared/headerfap.cshtml
@using Sitecore;
@using Primecomp93Helix.Feature.PageContent.Models
@model Header
<div class="to-header">
    <div class="row">
        <div class="col-sm-4 fapheaderleft">
            @if (Model != null && Model.Menu != null)
            {
                <a href="/"><img src="@Model.Menu.SiteLogoURL" class="img-responsive logo" /></a>
            }
            else
            {
                <img src="~/Images/bpm logo.png" class="img-responsive logo">
            }
        </div>
        <div class="col-md-4 fapheadercenter">
            <h1 class="fap-header">Provider Directory</h1>
        </div>
        <div class="col-sm-4 fapheaderright">
            <img src="~/Images/PrimeComp-PhysicianLookup.jpg" class="img-responsive" />
        </div>
    </div>
</div>
<!-- This is the middle Nav-->
<div class="header-nav-wrap">
    <nav class="navbar-inverse" data-spy="affix" data-offset-top="5">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <button type="button" class="navbar-toggle" data-toggle="modal" data-target="#myModal">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
            </div>
            <div class="navbar">
                <div class="collapse navbar-collapse" id="myNavbar">
                    <div class="container">
                        <ul class="nav top-nav">
                            <div class="dropdown">
                                <li class="dropbtn" data-title="">
                                    <a href="/">HOME</a>
                                </li>
                            </div>
                            @if (Model != null && Model.Nav != null)
                            {
                                foreach (var nav in Model.Nav)
                                {
                                    <div class="dropdown">
                                        <li class="dropbtn" data-title="">
                                            <a href='@nav.NavItemURL'>
                                                @nav.NavItemText
                                            </a>
                                        </li>

                                        @if (nav.NavLinks != null && nav.NavLinks.Count > 0)
                                        {
                                            <div class="dropdown-content">
                                                @foreach (var navLinks in nav.NavLinks)
                                                {
                                                    if (navLinks.NavLinkText == "Report Center")
                                                    {
                                                        if (Sitecore.Context.User.IsAuthenticated)
                                                        {
                                                            <a href="@navLinks.NavLinkURL">@navLinks.NavLinkText</a>
                                                        }
                                                    }
                                                    else
                                                    {
                                                        <a href='@navLinks.NavLinkURL'>@navLinks.NavLinkText</a>
                                                    }
                                                }
                                            </div>
                                        }
                                    </div>
                                }
                                if (Sitecore.Context.User.IsAuthenticated)
                                {
                                    var sitecoreString = "sitecore\\";
                                    var userName = Sitecore.Context.User.Name.ToString();
                                    userName = userName.Replace(sitecoreString, "");

                                    <div class="dropdown" style="float: right">
                                        @using (Html.BeginForm("logout", "Shared", FormMethod.Post))
                                        {
                                            <div style="padding-top:5px">
                                                <button name="logout" type="submit" value="logout" class="btn btn-info btn-md"><span class="glyphicon glyphicon-log-out"></span> Log out</button>
                                            </div>
                                        }
                                    </div>
                                    <div class="dropdown" style="float: right">

                                        <li class="dropbtn">
                                            @if (userName != null)
                                            {
                                                <div style="color:black; font-weight:bold"> @userName</div>
                                            }
                                        </li>
                                    </div>

                                }
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content nav-modal">
            <div class="modal-header nav-modal-head">
                <div class="row modal-icons-parent">
                    <ul class="modal-icons col-xs-12 list-style-none">
                        <div class="dropdown">
                            <li class="dropbtn" data-title="">
                                <a href="/">HOME</a>
                            </li>
                        </div>
                        @if (Model != null && Model.Menu != null && Model.MenuItems != null)
                        {
                            foreach (var menuItem in Model.MenuItems)
                            {
                                <li>
                                    <a href='@menuItem.MenuItemURL'>
                                        <figure><div class="imgicon"><img src='@menuItem.MenuItemLogo'></div><figcaption>@menuItem.MenuItemText</figcaption></figure>
                                    </a>
                                </li>
                            }
                        }
                    </ul>

                </div>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                @if (Model != null && Model.Nav != null)
                {
                    foreach (var nav in Model.Nav)
                    {
                        <label class="modal-navHeader"><a href='@nav.NavItemURL'>@nav.NavItemText</a></label>
                        if (nav.NavLinks != null && nav.NavLinks.Count > 0)
                        {
                            <div class="modal-navLinks">
                                <ul>
                                    @foreach (var navLinks in nav.NavLinks)
                                    {
                                        if (navLinks.NavLinkText == "Report Center")
                                        {
                                            if (Sitecore.Context.User.IsAuthenticated)
                                            {
                                                <a class=" fa fa-caret-right" href="@navLinks.NavLinkURL"> @navLinks.NavLinkText</a>
                                            }
                                        }
                                        else
                                        {
                                            <a class=" fa fa-caret-right" href='@navLinks.NavLinkURL'> @navLinks.NavLinkText</a>
                                        }

                                    }
                                </ul>
                            </div>
                        }
                    }
                    @*if (Sitecore.Context.User.IsAuthenticated)
                    {
                        <label class="modal-navHeader">
                            @using (Html.BeginForm("logout", "Shared", FormMethod.Post))
                            {
                                <button name="logout" type="submit" value="logout" class="bpp-logoutbtn-mbl">Logout</button>
                            }
                        </label>
                    }*@
                }
            </div>
        </div>
    </div>
</div>